CREATE TABLE tb_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL
);

CREATE TABLE tb_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE users_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES tb_users(id),
    FOREIGN KEY (role_id) REFERENCES tb_roles(id)
);

CREATE TABLE tb_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    validity_months INTEGER,
    description VARCHAR(255)
);

CREATE TABLE tb_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(255),
    active BOOLEAN
);

CREATE TABLE tb_patrimonies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patrimony_code VARCHAR(255) NOT NULL UNIQUE,
    tag VARCHAR(255) NOT NULL
);

CREATE TABLE tb_periodicities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_name VARCHAR(255) NOT NULL UNIQUE,
    days INTEGER NOT NULL
);

CREATE TABLE instruments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    manufacturer VARCHAR(255),
    model VARCHAR(255),
    serial_number VARCHAR(255),
    range VARCHAR(255),
    tolerance VARCHAR(255),
    resolution VARCHAR(255),
    category_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    patrimony_id BIGINT,
    periodicity_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    FOREIGN KEY (category_id) REFERENCES tb_categories(id),
    FOREIGN KEY (location_id) REFERENCES tb_locations(id),
    FOREIGN KEY (patrimony_id) REFERENCES tb_patrimonies(id),
    FOREIGN KEY (periodicity_id) REFERENCES tb_periodicities(id)
);

CREATE TABLE tb_calibrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calibration_date DATE,
    next_calibration_date DATE,
    certificate_number VARCHAR(255),
    laboratory VARCHAR(255),
    instrument_id BIGINT,
    FOREIGN KEY (instrument_id) REFERENCES instruments(id)
);

CREATE TABLE tb_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reason TEXT,
    instrument_id BIGINT NOT NULL,
    origin_id BIGINT,
    destination_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (instrument_id) REFERENCES instruments(id),
    FOREIGN KEY (origin_id) REFERENCES tb_locations(id),
    FOREIGN KEY (destination_id) REFERENCES tb_locations(id),
    FOREIGN KEY (user_id) REFERENCES tb_users(id)
);